### ISSUE TITLE
randomNum.js有错误

### ISSUE THREAD

**Issue by sfsoul** [proYang/outils#11]
假设范围为(2,10)，即min = 2,max = 10;
这时用 Math.floor(Math.random() * (max-min) + min)去求值是有错误的，因为永远输出不了10.
Math.random() * (max-min) = Math.random * 8,最大不可能为8，同理Math.floor(Math.random() * (max-min) + min)不可能输出10.
正确代码为：
Math.floor(Math.random() * (max-min+1) )+ min；

**Comment by proYang** [comment]
:rose: 感谢你的细心，已在[最新版本](https://github.com/proYang/outils/blob/master/src/random/randomNum.js)中更正了这个错误。
