### ISSUE TITLE
getOs 缺少一个 return （https://github.com/proYang/outils/blob/master/src/device/getOS.js）

### ISSUE THREAD

**Issue by linfengluo** [proYang/outils#13]
if (/iphone/i.test(userAgent) || /ipad/i.test(userAgent) || /ipod/i.test(userAgent)) 'ios'

**Comment by proYang** [comment]
:rose: 感谢你的细心，已在[最新版本](https://github.com/proYang/outils/blob/master/src/device/getOS.js)中更正了这个错误。
