### ISSUE TITLE
parseQueryString

### ISSUE THREAD

**Issue by makebanana** [proYang/outils#18]
return JSON.parse('{"' + decodeURIComponent(search).replace(/"/g, '\\"').replace(/&/g, '","').replace(/=/g, '":"') + '"}')

decodeURIComponent 过早了吧， 
& ， =  特殊字符
JSON.parse 之后 枚举处理吧

**Comment by proYang** [comment]
这里`replace`的本意，是将解码后的`url`查询字符串中的`&`，`=`等特殊字符串替换，拼接成一个类似的`JSON`字符串，然后再通过`JSON.parse()`方法转换为一个参数对象，不存在上述问题。

**Comment by makebanana** [comment]
encodeURIComponent('&') = '%26'
parseQueryString('www.baidu.com?a=123&b=%26')
make try

**Comment by proYang** [comment]
:rose: 感谢你的细心，已在[最新版本](https://github.com/proYang/outils/blob/master/src/url/parseQueryString.js)中更正了这个错误。
