### ISSUE TITLE
assert.notEqual

### ISSUE THREAD

**Issue by hjaiim** [proYang/outils#33]
assert.notEqual(outils.arrayEqual([0, 2, 3, 4], [1, 2, 3])) ,不管outils.arrayEqual()返回的结果是true或者false,这个测试应该都是可以通过的吧.
assert.notEqual() 我看api 好像不是这样用的.
大神能给解惑一下吗,是不是我的理解有误

**Comment by hjaiim** [comment]
是不是应该改写成这样,assert.notEqual(true, outils.arrayEqual([0, 2, 3, 4], [1, 2, 3]))

**Comment by proYang** [comment]
非常抱歉，的确是写错了。看了下API，期望值应该写在后面。`assert.notEqual(outils.arrayEqual([0, 2, 3, 4], [1, 2, 3]),true)`，但是`assert.notEqual(true, outils.arrayEqual([0, 2, 3, 4], [1, 2, 3]))`这样写也可以，最终不相等就可以了。非常感谢你的细心，后面会更正测试用例中的错误代码。:rose:

**Comment by hjaiim** [comment]
好的,好的
